### ISSUE TITLE
Qwikswitch Trigger YAML config for binary-sensor setup

### ISSUE THREAD

**Issue by andrew-w-roberts** [nardusleroux/hassio-qsusb#13]
Hi Guys,

I recently purchased another Qwikswitch 6-ch imod pulse module and when I went to replicate the YAML code I used for the other 4-ch imod pulse the binary-sensors in HA didn't work.  After using the ../&listen option to sniff the traffic from both I noticed that the cmd data in the message being sent by the new module was different - where this one uses the TOGGLE cmd not the success.data state.

Does anyone know how to configure the binary-sensor in YAML to enable the identification of the TOGGLE cmd data?

Currently I am using  this code for the other 4-ch imod, but somehow I need to identify the TOGGLE cmd data in the binary-senor:

qwikswitch:
   url: http://127.0.0.1:2020
   sensors: 
     - name: QSCH1
       id: "@259be0"
       channel: 1
       type: imod 

binary_sensor:
    #Qwikswitch Ch1
  - platform: qwikswitch
    sensors: 
      QwikswitchCh1:
        friendly_name: "Qwikswitch Ch1"
        device_class: motion
        **value_template: "{{ is_state('sensor.QSCH1', 'on') }}"**
        off_delay: 3
        qos: 1

**Comment by nardusleroux** [comment]
Hi @andrew-w-roberts 

Not sure this is issue for hassio-qsusb addon, since this addon just allows to containerise the qsusb application that should run on standalone Linux/Pi/Windows within hassio environment.
You should be looking at the Qwikswitch integration page for more hints at https://www.home-assistant.io/integrations/qwikswitch/
Seems Toggle is supported by integration.

**Comment by andrew-w-roberts** [comment]
Thank you for the feedback  I’ll request on the qwikswitch integrations page.
